### ISSUE TITLE
Repository Not Found 'github.com/mainflux/mainflux-auth/domain'

### ISSUE THREAD

**Issue by vahdet** [drasko/golang-auth-starter-kit#1]
In the services/users.go file,  the import repoitory "github.com/mainflux/mainflux-auth/domain" cannot be found apparently.

**Comment by drasko** [comment]
@vahdet unfinished due lack of time, try looking here: https://github.com/AtticFantastic/mainflux-auth

I copied most of the stuff, if you can finish and correct the project I'd gladly accept PRs.
